p_demux="0"
p_custom_string=" -r 10 -an -vcodec libx264 -crf 18 -preset superfast -filter:v setpts=0.10*PTS -f mp4"
p_v_codec="copy"
p_a_codec="copy"
p_size_width="1280"
p_size_height="720"
p_filter="null"
p_crf="18"
p_preset="ultrafast"
p_maxrate="1000k"
p_bufsize="1500k"
p_a_bitrate="192k"
p_g="60"
p_tune="fastdecode"
p_format="mp4"
p_fileext="mp4"
# NOT REQUIRED : set p_thumb_gen to "0" in .profile to ignore thumbnail generation
p_thumb_gen="1"
p_thumb_height="250"
p_thumb_rows="1"
p_thumb_cols="30"
