#!/bin/bash
#
# Description: lists players attached to the requested NGINX-RTMP publishing app
#

app=$1

if [ -z $1 ]; then
    echo "Sandy: Please provide me with an app id [c,d...z] to search for active connections."
fi

cd /vagrant/xndir/${content_type}

echo "'"

profiles=($(ls -d */))

for p in "${profiles[@]}"; do
    if [ "${profiles[-1]}" == "$p" ]; then
        echo "${p}"
    else 
        echo "${p};"
    fi
done

echo "'"
