#!/bin/bash
#
# Description: lists conversion profiles so that they can be populated elsewhere
#

content_type=$1

if [ -z $1 ]; then
    echo "Sandy: Please provide me with a content type [audio/video]"
fi

cd /vagrant/xndir/${content_type}

profiles=($(ls -d */))

for p in "${profiles[@]}"; do
    p=${p::-1}
    if [ "$p" == "raw" ]; then
        continue
    fi
    if [ "${profiles[-1]}" == "$p/" ]; then
        list="$list\"$p\""
    else 
        list="$list\"$p\","
    fi
done

echo "[$list]"
