#!/bin/bash
#
# Description: performs curl calls to the action services for the nginx-rtmp module
#

action=$1
app=$2
stream=$3

source /usr/local/bin/bistorm/vars/sandy_ip

if [ -z $action ] || [ -z $app ] || [ -z $stream ] ; then
    echo "Sandy: Please pass me an (1)app ([c,d..z]) (2)stream ([513,game]) (3)recorder name ([15sec,15min,audio,all]) and (4)action ([start,stop]) as arguments."
    echo "exit with error"
    exit 1
fi

echo "Sandy: I have received a request to $action recording of $app/$stream using the $rec recorder."

source /usr/local/bin/bistorm/vars/sandy_ip >/dev/null

## Stop Action
#    TODO: Discovery why we have to drop twice to get to 0

if [ "$action" == "stop" ]; then
echo $action
    curl http://$SANDY_IP/control/drop/publisher?app=r&name=$stream
    curl http://$SANDY_IP/control/drop/client?app=r&name=$stream
    echo "Sandy: The recording has been dropped."
    exit
fi;

ffmpeg -i rtmp://localhost/$app/$stream -codec copy -f flv rtmp://localhost/r/$stream >/dev/null &

echo "Sandy: My end has completed.  Raw recorded .flv files are temporarily stored in /vagrant/bistorm/xndir directories"
exit
