#!/bin/bash
#
# Description: storm init script for ubuntu system and user profiles

# Copy hosts file to /etc hosts
sudo cp /usr/local/bin/bistorm/conf/ubuntu/hosts /etc/hosts

# Copy Ubuntu profile configurations
sudo cp /usr/local/bin/bistorm/conf/ubuntu/ubuntu.profile ~/.profile >/dev/null
sudo chown vagrant:vagrant ~/.profile
sudo cp /usr/local/bin/bistorm/conf/ubuntu/rc.local /etc/rc.local >/dev/null

# Copy .ssh folder contents to user profile
sudo cp /usr/local/bin/bistorm/conf/ubuntu/ssh/* ~/.ssh/
sudo chown vagrant:vagrant ~/.ssh/* >/dev/null
cd ~/.ssh
for f in ./* ; do 
    if [ $(basename $f) == 'authorized_keys' ] || [ $(basename $f) == 'known_hosts' ]; then
        continue
    fi
    sudo chmod 600 ~/.ssh/* >/dev/null
done


