#!/bin/bash
#
# Description: Channel streamer for SLUG SiliconDust extension
#
echo "Sandy: I received a request to stop streaming ... " 
/vagrant/bistorm/stream/killswitch /var/www/hls /var/www/dash
echo "Sandy: Finished!"



