#!/bin/bash
#
# Description: Checks for existing client access 
#  and kills ffmpeg if no activity.  Run through CRON
#
warning=0

echo "Sandy: My daemon script ffmpeg-kill is running ..."
if [ $# -eq 0 ]
  then
    echo "Sandy: Please pass me directories to cleanse, like: 'ffmpeg_kill /var/www/public/hlsc /var/www/public/hlsd'"
    echo "Sandy: Pass carefully or I might just delete your project files. #JustKiddingILoveYou"
    echo "Sandy: But at least I won't undo your windows. #StillNotYourMaid"
    echo "Exit er 1"
    exit 1
fi

# Kill all media conversion processes on the server
count=`ps aux | grep -v "grep" | grep -c ffmpeg`
# ffmpeg daemon has 3 PIDs at all times.
if [ "${count}" -le 3 ]; then
    echo "Sandy: I wasn't running any conversions. #JustSoYouKnow"
else
    sudo killall ffmpeg
    echo "Sandy: My ffmpeg processes have been halted."
fi

# Clear Nginx if RTMP ports 1935 or 1981 are open
rtmp_guest_active=$(netstat -n | grep :1935 | grep ESTABLISHED )
rtmp_host_active=$(netstat -n | grep :1901 | grep ESTABLISHED )
if [ ! -z "$rtmp_guest_active" ] || [ ! -z "$rtmp_host_active" ]; then
    sudo nginx -s stop
    sudo nginx -s start
    echo "Sandy: My RTMP server has been restarted."
fi

#Iterate through all directories passed in
for var in "$@"
do
    [ ! -d $var ] && echo "Sandy: $var ? That's no directory, buster." && warning=1 && break
    [ -d $var ] && echo "Sandy: I'm emptying the streaming contents for $var ... "
    find $var -name "*.ts" -type f -delete
    find $var -name "*.m3u8" -type f -delete
    find $var -name "*.mp4" -type f -delete
done

if [ "${warning}" -eq 0 ]; then
    echo "Sandy: I am no longer streaming an HLS feed."
    echo "Sandy: ... she's dead, Jim."
fi

echo "Sandy: Done and done!"

#Free up memory
sudo sysctl -w vm.drop_caches=3 > /dev/null
