#!/bin/bash
#
# Description: storm is initiated after Sandy has booted. It has two use cases:
#   * crontab runs storm on reboot to re-provision some services
#     OR you can run storm after editing a bistorm/conf file to re-add it into the guest machine
#   * It is also a testbed for incorporating new libraries and technologies.
#   This is primarily so that our devs don't write 'test code' in prod files.
#   Write your functions here first, validate them, then extend as needed

flag_name="$1"
flag_binary="$2"

if [ -z $flag_name ]; then 
    exit 1;
fi

if [ -z $flag_binary ]; then
    exit 1;
fi

if [ $flag_binary == "1" ] ||  $flag_binary == 1 ]; then
    sudo touch "/vagrant/bistorm/flags/$flag_name"
fi

if [ $flag_binary == "0" ] ||  $flag_binary == 0 ]; then
    sudo rm "/vagrant/bistorm/flags/$flag_name"
fi