#!/bin/bash
#
# Description: Takes a raw flv file and dumps is as an .mp4 
#  to the convert/raw directory 
#
stream="$1"
copyto_v="$2"
copyto_a="$3"
echo "Sandy: I received a request to process $stream ..."
if [ ! -f $stream ] || [ ! ${stream: -4} == ".flv" ]; 
  then
    echo "Sandy: Please pass me an .flv file to process."
    echo "exited with error"
    exit 1
fi
if [ ! -d $copyto_v ]; 
    then
      echo "Sandy: Please pass me a directory to save the .mp4 into"
      echo "exited with error"
      exit 1
fi
if [ ! -d $copyto_a ]; 
    then
      echo "Sandy: Please pass me a directory to save the .aac into"
      echo "exited with error"
      exit 1
fi

# Get filename before .flv
mp4fn=$(basename "$stream")
mp4fn=$(echo $mp4fn | cut -f 1 -d '.')

# Folder organizer
foldername=$(date +%Y/%m/%d)
timestamp=$(date +'%s')
mkdir -p "$copyto_v/$foldername"
mkdir -p "$copyto_a/$foldername"

echo "Sandy: I am encapsulating the current stream $stream to $copyto_v/$mp4fn.mp4 and $copyto_v/$mp4fn.aac ... "

# Create demuxed .mp4, subs and audio, dump to $copyto folder 
ffmpeg -i $stream -vcodec copy -acodec copy "${copyto_v}/${foldername}/${mp4fn}_${timestamp}.mp4" > /dev/null
ffmpeg -i $stream -map 0:s:0 "${copyto_v}/${foldername}/${mp4fn}_${timestamp}.srt" > /dev/null
ffmpeg -i $stream -vn -acodec copy "${copyto_a}/${foldername}/${mp4fn}_${timestamp}.aac" > /dev/null


